### ISSUE TITLE
JWT secret not as a env variable

### ISSUE THREAD

**Issue by Karyum** [FACN4/week7-wdgaf#25]
https://github.com/FACN4/week7-wdgaf/blob/master/src/handlers/getUserDataHandler.js#L4

JWT secrets should never be visible in the code they should always be in an env var, cause take for example if youre using github as version control for your project then everyone can see the secret and decrypt the cookies, and change the values so he can access different sections of the website

**Comment by afifisuha** [comment]
now fixed, could u plz check and close
