### ISSUE TITLE
postLoginHandler file

### ISSUE THREAD

**Issue by Karyum** [FACN4/week7-wdgaf#28]
_i know might be a weird name for an issue it just has small bits that i need to talk about that don't deserve a separate issue each_

i noticed in [this line](https://github.com/FACN4/week7-wdgaf/blob/master/src/handlers/postLoginHandler.js#L7) you have the secret in the env var, then you just need to fix [this issue](#25).

jwt.verify is not used anywhere in the file _are you not using and fixing linter erros?_

i think this one is more of a personal thing but i like to have meaningful error argument names [not err2 :sweat_smile: ](https://github.com/FACN4/week7-wdgaf/blob/master/src/handlers/postLoginHandler.js#L31)

[the if statement here](https://github.com/FACN4/week7-wdgaf/blob/master/src/handlers/postLoginHandler.js#L22) you don't need to say ` if ( res === true )` instead you could do ` if (res)` cause it will check if it's truthy (and true is truthy :sweat_smile: )

**Comment by afifisuha** [comment]
now fixed could u plz check and close
